/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_pacificist_helloandroid_NativeService */

#ifndef _Included_com_android_pacificist_helloandroid_NativeService
#define _Included_com_android_pacificist_helloandroid_NativeService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_pacificist_helloandroid_NativeService
 * Method:    _start
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_android_pacificist_helloandroid_NativeService__1start
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_android_pacificist_helloandroid_NativeService
 * Method:    _print
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_android_pacificist_helloandroid_NativeService__1print
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
